/**
 * Regenerates photo-inbox/INDEX.md — a listing of every unpaired photo
 * with its dimensions, so the inbox stays browsable as it grows without
 * anyone hand-maintaining a table.
 *
 *   npx tsx lib/build-inbox-index.ts
 */
import { readdirSync, readFileSync, writeFileSync, statSync } from "fs";
import { join, extname } from "path";

const INBOX = join(process.cwd(), "photo-inbox");
const IMAGE_EXTENSIONS = new Set([".jpg", ".jpeg", ".png", ".webp", ".avif"]);

/** Reads intrinsic dimensions straight from the file header — no image lib needed. */
function dimensions(buf: Buffer): { w: number; h: number } | null {
  // PNG: IHDR width/height are fixed-offset big-endian uint32s.
  if (buf.length > 24 && buf.toString("hex", 0, 8) === "89504e470d0a1a0a") {
    return { w: buf.readUInt32BE(16), h: buf.readUInt32BE(20) };
  }
  // JPEG: walk the segment chain to the SOFn frame header.
  if (buf.length > 4 && buf[0] === 0xff && buf[1] === 0xd8) {
    let offset = 2;
    while (offset < buf.length - 9) {
      if (buf[offset] !== 0xff) {
        offset++;
        continue;
      }
      const marker = buf[offset + 1];
      const length = buf.readUInt16BE(offset + 2);
      // SOFn carries the dimensions; skip DHT/DAC/RSTn which reuse the range.
      const isSOF =
        marker >= 0xc0 && marker <= 0xcf && ![0xc4, 0xc8, 0xcc].includes(marker);
      if (isSOF) return { h: buf.readUInt16BE(offset + 5), w: buf.readUInt16BE(offset + 7) };
      offset += 2 + length;
    }
  }
  return null;
}

const files = readdirSync(INBOX)
  .filter((f) => IMAGE_EXTENSIONS.has(extname(f).toLowerCase()))
  .sort((a, b) => a.localeCompare(b, undefined, { numeric: true }));

/** eBay recommends >=1600px on the longest side for listing zoom to work. */
const ZOOM_MIN = 1600;

const measured = files.map((file) => ({
  file,
  d: dimensions(readFileSync(join(INBOX, file))),
  size: statSync(join(INBOX, file)).size,
}));

const rows = measured.map(({ file, d, size }) => {
  const shape = !d ? "unknown" : d.w === d.h ? "square" : "**not square**";
  const lowRes = d && Math.max(d.w, d.h) < ZOOM_MIN ? "**low-res**" : "";
  return `| \`${file}\` | ${d ? `${d.w}×${d.h}` : "?"} | ${shape} | ${lowRes} | ${(size / 1024).toFixed(0)} KB |`;
});

const notSquare = measured.filter(({ d }) => d && d.w !== d.h);
const lowRes = measured.filter(({ d }) => d && Math.max(d.w, d.h) < ZOOM_MIN);

writeFileSync(
  join(INBOX, "INDEX.md"),
  `# Inbox contents

Generated by \`npx tsx lib/build-inbox-index.ts\` — do not edit by hand.

**${files.length} unpaired photo(s).**

- **${notSquare.length} not square** — wants a crop before assignment. The
  storefront grid is 4:5 and marketplaces prefer square.
- **${lowRes.length} under ${ZOOM_MIN}px** on the longest side. eBay wants at
  least ${ZOOM_MIN}px for listing zoom to work, so these will look soft next to
  the 2400px shots. Usable, but re-export from the original at full size if
  the original still exists.

| File | Dimensions | Shape | Resolution | Size |
|---|---|---|---|---|
${rows.join("\n")}
`,
  "utf-8"
);

console.log(
  `Wrote photo-inbox/INDEX.md — ${files.length} file(s), ${notSquare.length} not square, ${lowRes.length} under ${ZOOM_MIN}px.`
);
