/**
 * Regenerates photo-inbox/INDEX.md — a listing of every unpaired photo
 * with its dimensions, so the inbox stays browsable as it grows without
 * anyone hand-maintaining a table.
 *
 *   npx tsx lib/build-inbox-index.ts
 */
import { readdirSync, readFileSync, writeFileSync, statSync } from "fs";
import { join, extname } from "path";

const INBOX = join(process.cwd(), "photo-inbox");
const IMAGE_EXTENSIONS = new Set([".jpg", ".jpeg", ".png", ".webp", ".avif"]);

/** Reads intrinsic dimensions straight from the file header — no image lib needed. */
function dimensions(buf: Buffer): { w: number; h: number } | null {
  // PNG: IHDR width/height are fixed-offset big-endian uint32s.
  if (buf.length > 24 && buf.toString("hex", 0, 8) === "89504e470d0a1a0a") {
    return { w: buf.readUInt32BE(16), h: buf.readUInt32BE(20) };
  }
  // JPEG: walk the segment chain to the SOFn frame header.
  if (buf.length > 4 && buf[0] === 0xff && buf[1] === 0xd8) {
    let offset = 2;
    while (offset < buf.length - 9) {
      if (buf[offset] !== 0xff) {
        offset++;
        continue;
      }
      const marker = buf[offset + 1];
      const length = buf.readUInt16BE(offset + 2);
      // SOFn carries the dimensions; skip DHT/DAC/RSTn which reuse the range.
      const isSOF =
        marker >= 0xc0 && marker <= 0xcf && ![0xc4, 0xc8, 0xcc].includes(marker);
      if (isSOF) return { h: buf.readUInt16BE(offset + 5), w: buf.readUInt16BE(offset + 7) };
      offset += 2 + length;
    }
  }
  return null;
}

const files = readdirSync(INBOX)
  .filter((f) => IMAGE_EXTENSIONS.has(extname(f).toLowerCase()))
  .sort((a, b) => a.localeCompare(b, undefined, { numeric: true }));

const rows = files.map((file) => {
  const buf = readFileSync(join(INBOX, file));
  const d = dimensions(buf);
  const size = statSync(join(INBOX, file)).size;
  const shape = !d ? "unknown" : d.w === d.h ? "square" : "**not square**";
  return `| \`${file}\` | ${d ? `${d.w}×${d.h}` : "?"} | ${shape} | ${(size / 1024).toFixed(0)} KB |`;
});

const notSquare = files.filter((file) => {
  const d = dimensions(readFileSync(join(INBOX, file)));
  return d && d.w !== d.h;
});

writeFileSync(
  join(INBOX, "INDEX.md"),
  `# Inbox contents

Generated by \`npx tsx lib/build-inbox-index.ts\` — do not edit by hand.

**${files.length} unpaired photo(s).** ${notSquare.length} not square, so they
want a crop before assignment: the storefront grid is 4:5 and marketplaces
prefer square.

| File | Dimensions | Shape | Size |
|---|---|---|---|
${rows.join("\n")}
`,
  "utf-8"
);

console.log(`Wrote photo-inbox/INDEX.md — ${files.length} file(s), ${notSquare.length} not square.`);
